In [2]:
print("helo")

helo

In [2]:
import pandas as pd

In [18]:
data={
    "Name":["John","able","miss","abel","abel","John"],
    "Age":[34,45,23,4,5,34]
}

#### data

In [19]:
df=pd.DataFrame(data)
df

   Name  Age
0  John   34
1  able   45
2  miss   23
3  abel    4
4  abel    5
5  John   34

In [8]:
print(df.columns)

Index(['Name', 'Age'], dtype='object')

In [9]:
filter_by_age= df['Age'] >= 30
filter_by_age

0     True
1     True
2    False
3    False
4    False
5     True
Name: Age, dtype: bool

In [10]:
df[filter_by_age]

   Name  Age
0  John   34
1  able   45
5  john   35

In [20]:
df.drop_duplicates()

   Name  Age
0  John   34
1  able   45
2  miss   23
3  abel    4
4  abel    5

In [23]:
ages = pd.Series([23,4,5],name='Age')

In [24]:
first_age=ages[0]

In [25]:
data = {'Category': ['A', 'B', 'A', 'B', 'A', 'B'],
        'Value': [10, 15, 20, 25, 30, 35]}

In [27]:
df1=pd.DataFrame(data)
df1

  Category  Value
0        A     10
1        B     15
2        A     20
3        B     25
4        A     30
5        B     35

In [31]:
grouped=df1.groupby('Category') 
grouped.size()

Category
A    3
B    3
dtype: int64

In [33]:
sum_values = grouped['Value'].sum()
sum_values

Category
A    60
B    75
Name: Value, dtype: int64